### ISSUE TITLE
f3dex2.s(840) error: Vector element index must be 4-byte aligned

### ISSUE THREAD

**Issue by mkst** [Mr-Wiseguy/f3dex2#1]
I'm getting this error on **master**, no build arguments specified. Not sure if I'm doing something wrong, or?

```sh
$ make
Building microcode: F3DEX2_2.08
f3dex2.s(840) error: Vector element index must be 4-byte aligned
Aborting.
make: *** [Makefile:152: F3DEX2_2.08/F3DEX2_2.08.code] Error 1
```
This is on Ubuntu 20.04 with a freshly compiled armips. I am seeing the same behaviour on Windows too.
```sh
$ armips
armips assembler v0.11.0 (Dec  3 2020 21:06:56) by Kingcom
Usage: armips [optional parameters] <FILE>

Optional parameters:
 -temp <TEMP>              Output temporary assembly data to <TEMP> file
 -sym  <SYM>               Output symbol data in the sym format to <SYM> file
 -sym2 <SYM2>              Output symbol data in the sym2 format to <SYM2> file
 -root <ROOT>              Use <ROOT> as working directory during execution
 -equ  <NAME> <VAL>        Equivalent to '<NAME> equ <VAL>' in code
 -strequ <NAME> <VAL>      Equivalent to '<NAME> equ "<VAL>"' in code
 -definelabel <NAME> <VAL> Equivalent to '.definelabel <NAME>, <VAL>' in code
 -erroronwarning           Treat all warnings like errors
 -stat                     Show area usage statistics

File arguments:
 <FILE>                    Main assembly code file
```

**EDIT:** It looks to have been caused by [this](https://github.com/Kingcom/armips/commit/73d907eed82e6848995014302016c9884ab733a7) commit to armips. I will try with an older commit.

Yup, [previous commit](https://github.com/Kingcom/armips/commit/10b827f4a951a1c8c4c64428dad84f51c801b179) builds fine:
```sh
$ make
Building microcode: F3DEX2_2.08
  F3DEX2_2.08 code matches
  F3DEX2_2.08 data matches
```

Not really sure if there's anything you can do about this...

**Comment by Mr-Wiseguy** [comment]
It seems the new armips build is unable to assemble the microcode no matter what offset I pick (even 0), so it seems to just be a bug in armips that will need to be resolved.
EDIT: I misread the error and the issue is the vector index, not the byte offset. The new armips is able to assemble the microcode if I change the index, but changing the index makes it impossible to match so the issue still remains.

**Comment by sp1187** [comment]
The recently added RSP validation has now been reverted, so the code should work again with the latest armips version.
